### PR TITLE
Adding vCHA backup scripts

### PR DESCRIPTION
**Pull request by chipzoller**
Adding vCHA backup scripts for pre- and post-job actions.

### CODE REVIEW

**Comment by poulpreben** [comment]
Hi @chipzoller. Thank you very much for this contribution. Could you please be so kind to add license, author and possibly sections to your README?

If you need inspiration, you can have a look at existing PowerShell scripts.

Thanks again!

- Preben

**Comment by chipzoller** [comment]
I'm having difficulty modifying my README to make it similar to one of your models. The formatting is not applying correctly even though I copied and pasted from your example. Would you perhaps be so kind as to making the changes just this once so I can see what you've done? In future submissions I can correct that.

Thanks,

Chip

**Comment by poulpreben** [comment]
Hi @chipzoller.

I have created an example file here, including the license section, and your credits.

https://pastebin.com/n0ZB7dmX

If you could please add those into the README.md file, and possibly add a few examples (including parameters) at the bottom, that would be very helpful. Do not worry about formatting - we can always fix that later. We care about the content, and not so much about the looks :)

**Comment by chipzoller** [comment]
@poulpreben Thank you, I have done so. Please let me know if the latest edits to README.md are acceptable.

**Comment by poulpreben** [comment]
Much better! Merging.

**Pull request merged**
