### PR TITLE
Make the script work with MFA accounts

### PR DESCRIPTION
**Pull request by kosli**
If M365 security defaults are used, then admin accounts need to be protected by MFA (Multi Factor Authentication)
-> the -credential parameters do not work with MFA accounts.
I added a parameter to the script so that it will pop up the M365 authentication dialog instead of the username/passwort form.

# Pull Request Template

By contributing, you agree that your contributions will be licensed under the projects original open source license.

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

### Type of change

* [x] Bug fix (non-breaking change which fixes an issue)
* [x] New feature (non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
* [ ] This change requires a documentation update

### How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

### Checklist (check all applicable):

* [x] My code follows the style guidelines of this project
* [x] I have performed a self-review of my own code
* [ ] I have commented my code, particularly in _hard to understand_ areas
* [ ] I have made corresponding changes to the documentation
* [x] My changes generate no new warnings
* [ ] I have added tests that prove my fix is effective or that my feature works
* [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by DChiavari** [comment]
Nice! Thanks for the contribution, I was not able to test with MFA.

**Comment by DChiavari** [comment]
Thanks, good catch

**Comment by kosli** [comment]
> Nice! Thanks for the contribution, I was not able to test with MFA.

are you going to merge the pull request or are you waiting for any input from my side?

**Comment by DChiavari** [comment]
I cannot merge pull requests, as I'm not one of the administrators of this repository.

**Comment by kosli** [comment]
@nielsengelen the change from this patch somehow didn't end up in the final merge/commit? i think my other pull request has "overwritten" the changes? shall i create a new pull request or can you somehow re-merge?

**Comment by nielsengelen** [comment]
It looks like it was overwritten or something. Can you make a new pull request so we have the correct merge?

**Comment by kosli** [comment]
@nielsengelen  see the new pull request #131 . Thanks

**Pull request merged**
